---
abstract: 'middlewares distribution'
author:
  - 'Kazuhiro Osawa <ko@yappo.ne.jp>'
build_requires:
  IO::Scalar: 0
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.790'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Engine-Middleware
no_index:
  directory:
    - inc
    - t
recommends:
  CGI::ExceptionManager: 0
  Data::Visitor::Encode: 0
  Encode: 0
  HTML::FillInForm: 2.00
  HTML::StickyQuery: 0
  HTTP::MobileAttribute: 0
  HTTP::Session: 0
  MIME::Types: 0
  Module::Reload: 0
  MouseX::Types: 0
  MouseX::Types::Path::Class: 0
  Path::Class: 0
  Scope::Upper: 0
  Text::SimpleTable: 0
requires:
  Any::Moose: 0.04
  HTTP::Engine: 0.1.4_02
  HTTP::Request: 0
  Mouse: 0.17
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08_02
